CREATE TABLE C168
(
CNO CHAR(9),
CNAME CHAR(8),
CSEX CHAR(2),
CAGE TINYINT,
CPROF CHAR(10),
PRIMARY KEY(CNO),
);


CREATE TABLE G168
(
 GNO CHAR(6),
GNAME CHAR(12),
CATEGORY CHAR(10),
PRICE MONEY	,
PRIMARY KEY(GNO),
);

CREATE TABLE S168
(
 SNO CHAR(5),
SNAME CHAR(12),
SCITY CHAR(10),
PRIMARY KEY(SNO),
);

CREATE TABLE CGS168
(
CNO	CHAR(9),
GNO	CHAR(6),
SNO	CHAR(5),
QTY TINYINT	,
PRIMARY KEY(CNO,GNO,SNO),
FOREIGN KEY(CNO) REFERENCES C168(CNO),
FOREIGN KEY(GNO) REFERENCES G168(GNO),
FOREIGN KEY(SNO) REFERENCES S168(SNO),
);


--1)	查询“家居”类价格介于至之间（包括和）的商品信息
SELECT * FROM G168
WHERE CATEGORY = '家居' AND PRICE BETWEEN 500 AND 2000;


--2)	查询从事行业以“计算”开头且与本人同性别
--（本人男性则查询男性，本人女性则查询女性）的客户信息
SELECT * FROM C168
WHERE CPROF LIKE '计算%' AND CSEX = '女';


--3)	查询自己的购物记录（以客户代号为查询条件，显示结果表头为：姓名，商品名称，商家名称，单价，数量，总价）
SELECT CNAME,GNAME,SNAME,PRICE,QTY,PRICE*QTY AS SUMPRICE
FROM C168,G168,S168,CGS168
WHERE CGS168.CNO = 'E01914168' AND CGS168.CNO=C168.CNO AND CGS168.GNO=G168.GNO AND CGS168.SNO=S168.SNO

--4)	查询单次交易数量大于所有交易平均数量的客户姓名
SELECT CNAME FROM C168
WHERE CNO IN(

SELECT CNO FROM CGS168
WHERE QTY >= (
SELECT AVG(QTY)
FROM CGS168
)
)

--5)	查询商品“茶几”销量前的销售记录对应的
--客户姓名、从事行业、商家名称和销售数量，按销量从高到低显示
SELECT CNAME,CPROF,SNAME,QTY
FROM C168,S168,CGS168
WHERE CGS168.CNO=C168.CNO AND CGS168.SNO=S168.SNO AND 
QTY IN(
SELECT TOP 3 QTY
FROM CGS168
ORDER BY QTY DESC
)

--6)	查询用户王蒙没有购买的商品信息
SELECT * FROM G168
WHERE GNO !=ALL
(
SELECT GNO FROM CGS168
WHERE CNO IN(
SELECT CNO FROM C168
WHERE CNAME = '王蒙'
)
)


--7)	将自己购买商家“”的“沙发”的购物记录插入销售记录表中，
---购买数量为(应该在插入语句中利用查询给出“沙发”的商品代号)；
INSERT 
INTO CGS168(CNO,GNO,SNO,QTY)
SELECT 'E01914168',GNO,'10001',5 FROM G168
WHERE GNAME='沙发'


--8)	删除客户“王蒙”的购物信息
DELETE 
FROM CGS168
WHERE CNO IN (
SELECT CNO 
FROM C168
WHERE CNAME='王蒙'
)


--9)	将所有用户购买的“茶几”的数量调整为原先的倍；
UPDATE CGS168
SET QTY = QTY*2
WHERE GNO IN(
SELECT GNO FROM G168
WHERE GNAME='茶几'
)


--10)	建立一个从事计算机行业的客户购买"茶几"的视图CGS_CSCJ，通过视图查询显示结果。
CREATE VIEW CGS_CSCJ AS SELECT *
FROM CGS168
WHERE 
GNO IN(
	SELECT GNO FROM G168
	WHERE GNAME='茶几')
AND CNO IN (SELECT CNO FROM C168
	WHERE CPROF='计算机')

