DATA SEGMENT
	N1 DD 234B8074H
	N2 DD 658A1D61H
	N3 DD ?
DATA ENDS
CODE SEGMENT
	ASSUME CS:CODE,DS:DATA
START:
	MOV AX,DATA
	MOV DS,AX
	MOV AX,WORD PTR N1
	MOV DX,WORD PTR N1+2
	MOV CX,WORD PTR N2
	MOV BX,WORD PTR N2+2
	ADD AX,CX
	ADC DX,BX
	MOV WORD PTR N3,AX
	MOV WORD PTR N3+2,DX
	MOV AH,4CH
	INT 21H
CODE ENDS
	END START